# Generated by Django 6.1 on 2026-08-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='niveau',
            field=models.CharField(blank=True, choices=[('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3'), ('M1', 'M1'), ('M2', 'M2')], max_length=5, null=True),
        ),
    ]
