# Generated by Django 6.1 on 2026-08-18 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QCM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cours', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOuverte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('reponse_correcte', models.TextField()),
                ('points', models.FloatField(default=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Devoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('contenu', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoirs_crees', to=settings.AUTH_USER_MODEL)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoirs_recus', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('type_question', models.CharField(choices=[('qcm', 'QCM'), ('ouverte', 'Question ouverte')], default='qcm', max_length=20)),
                ('reponse_correcte', models.TextField(blank=True)),
                ('qcm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='qcm.qcm')),
            ],
        ),
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=500)),
                ('est_correcte', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propositions', to='qcm.question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionDevoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(default=1)),
                ('devoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_devoir', to='qcm.devoir')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoirs', to='qcm.questionouverte')),
            ],
            options={
                'ordering': ['ordre'],
                'unique_together': {('devoir', 'question')},
            },
        ),
        migrations.CreateModel(
            name='ReponseDevoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse_etudiant', models.TextField(blank=True)),
                ('score', models.FloatField(default=0)),
                ('note', models.FloatField(default=0)),
                ('resultat', models.CharField(blank=True, max_length=100)),
                ('niveau', models.CharField(blank=True, max_length=100)),
                ('date_reponse', models.DateTimeField(auto_now=True)),
                ('devoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='qcm.devoir')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_devoir', to='qcm.questionouverte')),
            ],
            options={
                'unique_together': {('devoir', 'question')},
            },
        ),
    ]
