# Generated by Django 6.1 on 2026-08-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0002_devoir_termine'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcm',
            name='niveau',
            field=models.CharField(choices=[('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3'), ('M1', 'M1'), ('M2', 'M2')], default='L1', max_length=5),
        ),
    ]
